### ISSUE TITLE
requests.exceptions.SSLError: HTTPSConnectionPool(host='dapi.binance.us', port=443)

### ISSUE THREAD

**Issue by wenjtop** [Binance-docs/binance-futures-connector-python#177]
Traceback (most recent call last):
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/urllib3/connectionpool.py", line 598, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/urllib3/connection.py", line 319, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1133)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dapi.binance.us', port=443): Max retries exceeded with url: /dapi/v1/time (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wenjtop/binance-futures-connector-python/test1.py", line 6, in <module>
    print(cm_futures_client.time())
  File "/Users/wenjtop/binance-futures-connector-python/binance/cm_futures/market.py", line 32, in time
    return self.query(url_path)
  File "/Users/wenjtop/binance-futures-connector-python/binance/api.py", line 69, in query
    return self.send_request("GET", url_path, payload=payload)
  File "/Users/wenjtop/binance-futures-connector-python/binance/api.py", line 116, in send_request
    response = self._dispatch_request(http_method)(**params)
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wenjtop/miniconda3/envs/wenjtop/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='dapi.binance.us', port=443): Max retries exceeded with url: /dapi/v1/time (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))

please help me

**Comment by alplabin** [comment]
Hi @wenjtop , we have released a new [modularised version of the Python Connector](https://github.com/binance/binance-connector-python) and the `binance-futures-connector-python` will not be maintained anymore. I suggest you to start using the new one and open a new issue at the modularised connector, if you still encounter it.
